export const testMusicArr = [
  "ABBA",
  "AC/DC",
  "Aerosmith",
  "Alice Cooper",
  "Alicia Keys",
  "Allman Brothers Band",
  "Amadou and Mariam",
  "Andrews Sisters",
  "Animals",
  "Arcade Fire",
  "Band",
  "Beach Boys",
  "Beastie Boys",
  "Beatles",
  "Bee Gees",
  "Big Star",
  "Black Flag",
  "Black Sabbath",
  "Blondie",
  "Booker T. and the MG’s",
  "Boston",
  "Boswell Sisters",
  "Boyz II Men",
  "Britney Spears",
  "Brooks & Dunn",
  "Bruno Mars",
  "Buffalo Springfield",
  "Byrds",
  "Calle 13",
  "Chemical Brothers",
  "Chicago",
  "Clash",
  "Coasters",
  "Coldplay",
  "Cream",
  "Creedence Clearwater Revival",
  "Crosby, Stills & Nash",
  "Daft Punk",
  "David Guetta",
  "De La Soul",
  "Death Cab for Cutie",
  "Decemberists",
  "Def Leppard",
  "Devo",
  "Dillards",
  "Dion and the Belmonts",
  "Dire Straits",
  "Dixie Chicks",
  "Doors",
  "Drifters",
  "Eagles",
  "Earth, Wind & Fire",
  "Elton John",
  "Elvis Presley",
  "Emerson Lake & Palmer",
  "Eminem",
  "Everly Brothers",
  "Flamingos",
  "Fleetwood Mac",
  "Flying Burrito Brothers",
  "Four Seasons",
  "Four Tops",
  "Frankie Lymon and the Teenagers",
  "Fugazi",
  "Gang of Four",
  "Genesis",
  "Gladys Knight and the Pips",
  "Grandmaster Flash and the Furious Five",
  "Grateful Dead",
  "Green Day",
  "Guns N' Roses",
  "Harry Styles",
  "Hollies",
  "HüskerDü",
  "Iggy and the Stooges",
  "Ink Spots",
  "Isley Brothers",
  "Jam",
  "Jefferson Airplane",
  "Jennifer Lopez",
  "Jesus and Mary Chain",
  "Jonas Brothers",
  "Journey",
  "Joy Division",
  "Judds",
  "Justin Bieber",
  "Justin Timberlake",
  "Katy Perry",
  "Kingston Trio",
  "Kinks",
  "Kool and the Gang",
  "Kraftwerk",
  "Lady Gaga",
  "Ladysmith Black Mambazo",
  "Led Zeppelin",
  "Little Anthony and the Imperials",
  "Louvin Brothers",
  "Love",
  "Lovin’ Spoonful",
  "LynyrdSkynyrd",
  "MC5",
  "Madonna",
  "Malumba",
  "Mariah Carey",
  "Maroon 5",
  "Mekons",
  "Metallica",
  "Mills Brothers",
  "Modest Mouse",
  "Monkees",
  "Moody Blues",
  "Moonglows",
  "Mumford & Sons",
  "My Chemical Romance",
  "New Order",
  "New York Dolls",
  "Nine Inch Nails",
  "Nirvana",
  "No Doubt",
  "Ohio Players",
  "One Direction",
  "OutKast",
  "O’Jays",
  "Parliament-Funkadelic",
  "Pavement",
  "Pearl Jam",
  "Pere Ubu",
  "Peter, Paul and Mary",
  "Pink",
  "Pink Floyd",
  "Pitbull",
  "Pixies",
  "Poco",
  "Portishead",
  "Public Enemy",
  "Puffy AmiYumi",
  "Queen",
  "R.E.M.",
  "Radiohead",
  "Rage Against the Machine",
  "Ramones",
  "Rascal Flatts",
  "Red Hot Chili Peppers",
  "Replacements",
  "Ricky Martin",
  "Rihanna",
  "Rolling Stones",
  "Roxy Music",
  "Run-D.M.C.",
  "Sam and Dave",
  "Santana",
  "Selena Gomez",
  "Sex Pistols",
  "Shadows",
  "Shakira",
  "Shirelles",
  "Sleater-Kinney",
  "Sly and the Family Stone",
  "Smashing Pumpkins",
  "Smiths",
  "Snoop Dog",
  "Sonic Youth",
  "Soul Stirrers",
  "Spice Girls",
  "Stanley Brothers",
  "Staple Singers",
  "Steely Dan",
  "Strokes",
  "TV on the Radio",
  "Talking Heads",
  "Taylor Swift",
  "Television",
  "Temptations",
  "The Mamas and the Papas",
  "The Beatles",
  "The Orioles",
  "The Pet Shop Boys",
  "The Platters",
  "The Police",
  "The Turtles",
  "The Who",
  "Tinariwen",
  "Toots and the Maytals",
  "Traffic",
  "U2",
  "Van Halen",
  "Velvet Underground",
  "Weavers",
  "White Stripes",
  "Wilco",
  "Yardbirds",
  "Yes",
  "Yo La Tengo",
  "ZZ Top"
];
