export const testMusicArr = [
  "Madonna",
  "Britney Spears",
  "Malumba",
  "Genesis",
  "Metallica",
  "Elvis Presley",
  "Taylor Swift",
  "Eminem",
  "Elton John",
  "Nirvana",
  "Justin Bieber",
  "Lady Gaga",
  "Rihanna",
  "Katy Perry",
  "Bruno Mars",
  "Shakira",
  "Justin Timberlake",
  "Jennifer Lopez",
  "Selena Gomez",
  "Pink",
  "Alicia Keys",
  "Harry Styles",
  "One Direction",
  "Snoop Dog",
  "Pitbull",
  "Mariah Carey",
  "Ricky Martin",
  "David Guetta",
  "No Doubt",
  "U2",
  "Led Zeppelin",
  "Queen",
  "Pink Floyd",
  "Rolling Stones",
  "Eagles",
  "AC/DC",
  "Guns N' Roses",
  "Aerosmith",
  "Red Hot Chili Peppers",
  "Maroon 5",
  "Journey"
];
